version: '3.8'

services:
  db_postgres:
    container_name: postgres-container
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ports:
       - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    container_name: nest-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_PORT: ${POSTGRES_PORT}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db_postgres
    networks:
      - app-network
    volumes:
      - ./src:/app/src

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge